server:
  port: 8761
  shutdown: graceful
  servlet:
    context-path: /eureka

spring:
  application:
    name: eventor-eureka
  lifecycle:
    timeout-per-shutdown-phase: 10s
  profiles:
    active: dev
  security:
    user:
      name: root
      password: 1q2w3e4r!

logging:
  file:
    path: ./logs
