server:
  port: 8761
  shutdown: graceful

spring:
  application:
    name: eventor-eureka
  lifecycle:
    timeout-per-shutdown-phase: 10s
  profiles:
    active: dev
  security:
    user:
      name: ${EUREKA_USERNAME}
      password: ${EUREKA_PASSWORD}

logging:
  file:
    path: ./logs
